// data.js
// This file acts as a central database for the Bazaar Odisha prototype.
// It contains all business, product, and worker information for the entire application.

const allBusinesses = [
    // Electricians
    { id: 1, name: 'Balangir Tech Repair', category: 'electrician', location: 'Balangir', lat: 20.7143, lng: 83.4975, phone: '9876543210', tags: ['women-owned'], description: 'Led by a team of skilled female technicians, we offer reliable and fast solutions for all household electrical issues. We prioritize safety and customer satisfaction.', image: 'images/business_balangir_tech_repair.webp', gallery: ['images/business_balangir_tech_repair_1.webp', 'images/business_balangir_tech_repair_2.webp', 'images/business_balangir_tech_repair_3.webp'] },
    { id: 5, name: 'Puri Electricals', category: 'electrician', location: 'Puri', lat: 19.8135, lng: 85.8312, phone: '9876543214', tags: [], description: 'Serving the Puri area with fast and efficient electrical services for homes, hotels, and businesses. Available 24/7 for emergency call-outs.', image: 'images/business_puri_electricals.webp', gallery: ['images/gallery_electrician_1.webp', 'images/gallery_electrician_2.webp', 'images/gallery_electrician_3.webp'] },
    
    // Plumbers
    { id: 2, name: 'Maa Pataneswari Plumbers', category: 'plumber', location: 'Balangir', lat: 20.7190, lng: 83.4901, phone: '9876543211', tags: [], description: 'Your trusted local plumbing service in Balangir for over 15 years. We handle everything from leaky faucets to complete pipeline installations for new homes.', image: 'images/business_pataneswari_plumbers.webp', gallery: ['images/gallery_plumber_1.webp', 'images/gallery_plumber_2.webp', 'images/gallery_plumber_3.webp'] },
    { id: 6, name: 'Cuttack Plumbing Co.', category: 'plumber', location: 'Cuttack', lat: 20.4625, lng: 85.8830, phone: '9876543215', tags: [], description: 'The go-to plumbing solution in Cuttack for residential and commercial properties. We offer transparent pricing and guaranteed work.', image: 'images/business_cuttack_plumbing.webp', gallery: ['images/gallery_plumber_1.webp', 'images/gallery_plumber_2.webp', 'images/gallery_plumber_3.webp'] },
    { id: 20, name: 'Sambalpur Water Solutions', category: 'plumber', location: 'Sambalpur', lat: 21.4704, lng: 83.9733, phone: '9876543239', tags: [], description: 'Specialists in water tank installation, pipeline maintenance, and bathroom fittings in the Sambalpur area.', image: 'images/business_sambalpur_water.webp', gallery: ['images/gallery_plumber_1.webp', 'images/gallery_plumber_2.webp', 'images/gallery_plumber_3.webp'] },

    // Groceries, Spices, Food & Tiffin
    { id: 3, name: 'Daily Needs Grocery', category: 'grocery', location: 'Balangir', lat: 20.7085, lng: 83.5012, phone: '9876543212', tags: ['eco-friendly'], description: 'We provide fresh, locally-sourced vegetables and groceries. We are proud to use eco-friendly packaging and support local farmers in the Balangir district.', image: 'images/business_daily_needs_grocery.webp', gallery: ['images/gallery_grocery_1.webp', 'images/gallery_grocery_2.webp', 'images/gallery_grocery_3.webp'] },
    { id: 7, name: 'Bhubaneswar Fresh Mart', category: 'grocery', location: 'Bhubaneswar', lat: 20.2961, lng: 85.8245, phone: '9876543216', tags: ['eco-friendly'], description: 'A modern grocery store in the heart of Bhubaneswar focusing on organic products and sustainable sourcing. We offer home delivery services.', image: 'images/business_bhubaneswar_fresh_mart.webp', gallery: ['images/gallery_grocery_1.webp', 'images/gallery_grocery_2.webp', 'images/gallery_grocery_3.webp'] },
    { id: 13, name: 'Maa Annapurna Tiffin', category: 'tiffin-service', location: 'Cuttack', lat: 20.4735, lng: 85.8953, phone: '9876543222', tags: ['women-owned', 'eco-friendly'], description: 'Delicious and hygienic home-cooked meals delivered to your doorstep. Specializing in authentic Odia thalis for lunch and dinner.', image: 'images/business_annapurna_tiffin.webp', gallery: ['images/gallery_tiffin_1.webp', 'images/gallery_tiffin_2.webp', 'images/gallery_tiffin_3.webp'] },
    { id: 24, name: 'Sambalpur Organic Spices', category: 'spices', location: 'Sambalpur', lat: 21.465, lng: 83.978, phone: '9876543243', tags: ['women-owned'], description: 'Authentic, hand-ground spices made from organic ingredients. Our special blends bring the true taste of Sambalpur to your kitchen.', image: 'images/business_sambalpur_organic_spices.webp', gallery: ['images/business_sambalpur_organic_spices_1.webp', 'images/business_sambalpur_organic_spices_2.webp', 'images/business_sambalpur_organic_spices_3.webp'] },
    { id: 31, name: 'Ganjam Pickle Makers', category: 'pickles', location: 'Ganjam', lat: 19.379, lng: 84.823, phone: '9876543250', tags: ['women-owned'], description: 'Traditional and mouth-watering pickles made with love by the women of Ganjam, using sun-drying techniques for authentic flavor.', image: 'images/business_ganjam_pickle_makers.webp', gallery: ['images/business_ganjam_pickle_makers_1.webp', 'images/business_ganjam_pickle_makers_2.webp', 'images/business_ganjam_pickle_makers_3.webp'] },
    { id: 34, name: 'Gajapati Sweets', category: 'sweets', location: 'Gajapati', lat: 18.777, lng: 84.133, phone: '9876543253', tags: [], description: 'Home of the famous Gajapati ladoo and other traditional Odia sweets. Made with pure ghee and the finest ingredients.', image: 'images/business_gajapati_sweets.webp', gallery: ['images/business_gajapati_sweets_1.webp', 'images/business_gajapati_sweets_2.webp', 'images/business_gajapati_sweets_3.webp'] },
    { id: 29, name: 'Koraput Millet Farmers', category: 'millets', location: 'Koraput', lat: 18.816, lng: 82.716, phone: '9876543248', tags: ['eco-friendly'], description: 'A collective of farmers providing organic millets like Ragi and Suan, sourced directly from the pristine hills of Koraput.', image: 'images/business_koraput_millet_farmers.webp', gallery: ['images/business_koraput_millet_farmers_1.webp', 'images/business_koraput_millet_farmers_2.webp', 'images/business_koraput_millet_farmers_3.webp'] },

    // Handicrafts & Textiles
    { id: 25, name: 'Cuttack Handloom Emporium', category: 'handloom', location: 'Cuttack', lat: 20.470, lng: 85.880, phone: '9876543244', tags: [], description: 'A curated collection of the finest handloom sarees and textiles from all over Odisha, located in the silver city.', image: 'images/business_cuttack_handloom_emporium.webp', gallery: ['images/business_cuttack_handloom_emporium_1.webp', 'images/business_cuttack_handloom_emporium_2.webp', 'images/business_cuttack_handloom_emporium_3.webp'] },
    { id: 26, name: 'Puri Pattachitra Studio', category: 'pattachitra', location: 'Puri', lat: 19.809, lng: 85.828, phone: '9876543245', tags: [], description: 'Authentic Pattachitra paintings on palm leaf and tussar silk, created by national award-winning artists from Raghurajpur.', image: 'images/business_puri_pattachitra_studio.webp', gallery: ['images/business_puri_pattachitra_studio_1.webp', 'images/business_puri_pattachitra_studio_2.webp', 'images/business_puri_pattachitra_studio_3.webp'] },
    { id: 27, name: 'Berhampur Silk House', category: 'silk-saree', location: 'Berhampur', lat: 19.310, lng: 84.790, phone: '9876543246', tags: [], description: 'The official home of the famous Berhampuri Patta, also known as the "Silk City" sarees, GI-tagged for their unique weaving style.', image: 'images/business_berhampur_silk_house.webp', gallery: ['images/business_berhampur_silk_house_1.webp', 'images/business_berhampur_silk_house_2.webp', 'images/business_berhampur_silk_house_3.webp'] },
    { id: 28, name: 'Rourkela Metal Crafts', category: 'metal-craft', location: 'Rourkela', lat: 22.255, lng: 84.850, phone: '9876543247', tags: [], description: 'Exquisite Dhokra and wrought iron crafts that showcase the tribal heritage of the Sundargarh region.', image: 'images/business_rourkela_metal_crafts.webp', gallery: ['images/business_rourkela_metal_crafts_1.webp', 'images/business_rourkela_metal_crafts_2.webp', 'images/business_rourkela_metal_crafts_3.webp'] },
    { id: 30, name: 'Bhubaneswar Tribal Jewelry', category: 'jewelry', location: 'Bhubaneswar', lat: 20.270, lng: 85.840, phone: '9876543249', tags: ['women-owned'], description: 'A stunning collection of tribal jewelry, featuring designs from the Dongria Kondh and Saura communities.', image: 'images/business_bhubaneswar_tribal_jewelry.webp', gallery: ['images/business_bhubaneswar_tribal_jewelry_1.webp', 'images/business_bhubaneswar_tribal_jewelry_2.webp', 'images/business_bhubaneswar_tribal_jewelry_3.webp'] },
    { id: 32, name: 'Jajpur Terracotta Works', category: 'terracotta', location: 'Jajpur', lat: 20.852, lng: 86.338, phone: '9876543251', tags: [], description: 'Beautifully crafted terracotta pottery, idols, and decorative items from the artisan villages of Jajpur.', image: 'images/business_jajpur_terracotta_works.webp', gallery: ['images/business_jajpur_terracotta_works_1.webp', 'images/business_jajpur_terracotta_works_2.webp', 'images/business_jajpur_terracotta_works_3.webp'] },
    { id: 33, name: 'Bargarh Handloom Weavers', category: 'handloom', location: 'Bargarh', lat: 21.336, lng: 83.623, phone: '9876543252', tags: [], description: 'The heartland of Sambalpuri Ikat. Discover a wide range of sarees, dress materials, and home furnishings.', image: 'images/business_bargarh_handloom_weavers.webp', gallery: ['images/business_bargarh_handloom_weavers_1.webp', 'images/business_bargarh_handloom_weavers_2.webp', 'images/business_bargarh_handloom_weavers_3.webp'] },
    { id: 35, name: 'Kendrapara Golden Grass Works', category: 'golden-grass', location: 'Kendrapara', lat: 20.503, lng: 86.419, phone: '9876543254', tags: ['women-owned'], description: 'Eco-friendly and chic bags, hats, and home decor made from the shimmering Golden Grass (Kaincha), crafted by local women artisans.', image: 'images/business_kendrapara_golden_grass_works.webp', gallery: ['images/business_kendrapara_golden_grass_works_1.webp', 'images/business_kendrapara_golden_grass_works_2.webp', 'images/business_kendrapara_golden_grass_works_3.webp'] },
    { id: 36, name: 'Sonepur Bomkai Creations', category: 'bomkai-saree', location: 'Sonepur', lat: 20.857, lng: 83.906, phone: '9876543255', tags: [], description: 'Exclusive showroom for the famous Bomkai sarees, known for their intricate threadwork and traditional motifs.', image: 'images/business_sonepur_bomkai_creations.webp', gallery: ['images/business_sonepur_bomkai_creations_1.webp', 'images/business_sonepur_bomkai_creations_2.webp', 'images/business_sonepur_bomkai_creations_3.webp'] },
    { id: 37, name: 'Mayurbhanj Sabai Crafts', category: 'sabai-crafts', location: 'Mayurbhanj', lat: 21.938, lng: 86.737, phone: '9876543256', tags: ['women-owned'], description: 'Discover a range of durable and artistic furniture, ropes, and decorative items made from Sabai grass.', image: 'images/business_mayurbhanj_sabai_crafts.webp', gallery: ['images/business_mayurbhanj_sabai_crafts_1.webp', 'images/business_mayurbhanj_sabai_crafts_2.webp', 'images/business_mayurbhanj_sabai_crafts_3.webp'] },
    { id: 38, name: 'Pipili Applique Traders', category: 'applique', location: 'Pipili', lat: 20.124, lng: 85.833, phone: '9876543257', tags: [], description: 'The hub for Odisha’s famous Applique (Chandua) work. Find vibrant wall hangings, umbrellas, and garden accessories.', image: 'images/business_pipili_applique_traders.webp', gallery: ['images/business_pipili_applique_traders_1.webp', 'images/business_pipili_applique_traders_2.webp', 'images/business_pipili_applique_traders_3.webp'] },

    // Repair & Maintenance
    { id: 11, name: 'Rourkela Wood Works', category: 'carpenter', location: 'Rourkela', lat: 22.2492, lng: 84.8536, phone: '9876543220', tags: [], description: 'Custom furniture, door/window fitting, and all kinds of wooden repairs. Serving Rourkela for over 20 years with quality craftsmanship.', image: 'images/business_rourkela_wood_works.webp', gallery: ['images/gallery_carpenter_1.webp', 'images/gallery_carpenter_2.webp', 'images/gallery_carpenter_3.webp'] },
    { id: 12, name: 'Capital City Painters', category: 'painter', location: 'Bhubaneswar', lat: 20.2825, lng: 85.8295, phone: '9876543221', tags: [], description: 'Professional interior and exterior painting services. We use high-quality, durable paints for a perfect finish every time.', image: 'images/business_capital_painters.webp', gallery: ['images/gallery_painter_1.webp', 'images/gallery_painter_2.webp', 'images/gallery_painter_3.webp'] },
    { id: 14, name: 'Berhampur PC Solutions', category: 'computer-repair', location: 'Berhampur', lat: 19.3137, lng: 84.7939, phone: '9876543223', tags: [], description: 'Your one-stop shop for all computer and laptop repairs. We handle software issues, hardware upgrades, and virus removal.', image: 'images/business_berhampur_pc.webp', gallery: ['images/gallery_computer_1.webp', 'images/gallery_computer_2.webp', 'images/gallery_computer_3.webp'] },
    { id: 15, name: 'Cool Breeze AC Service', category: 'ac-repair', location: 'Bhubaneswar', lat: 20.2917, lng: 85.8166, phone: '9876543224', tags: [], description: 'Fast and reliable AC installation, repair, and maintenance services for all brands. Keep your home cool with our expert technicians.', image: 'images/business_cool_breeze_ac.webp', gallery: ['images/gallery_ac_1.webp', 'images/gallery_ac_2.webp', 'images/gallery_ac_3.webp'] },
    { id: 17, name: 'Home Appliance Repair', category: 'appliance-repair', location: 'Rourkela', lat: 22.2604, lng: 84.8536, phone: '9876543236', tags: [], description: 'Expert repair for washing machines, refrigerators, microwaves, and other home appliances. Quick service at your doorstep.', image: 'images/business_home_appliance_repair.webp', gallery: ['images/gallery_appliance_1.webp', 'images/gallery_appliance_2.webp', 'images/gallery_appliance_3.webp'] },
    { id: 18, name: 'Puri Wall Artists', category: 'painter', location: 'Puri', lat: 19.8052, lng: 85.8248, phone: '9876543237', tags: ['women-owned'], description: 'Transform your walls with beautiful paintings and textures. We specialize in creative and artistic wall designs for homes and businesses.', image: 'images/business_puri_wall_artists.webp', gallery: ['images/gallery_painter_1.webp', 'images/gallery_painter_2.webp', 'images/gallery_painter_3.webp'] },
    { id: 19, name: 'Cuttack Furniture Makers', category: 'carpenter', location: 'Cuttack', lat: 20.476, lng: 85.877, phone: '9876543238', tags: [], description: 'Bespoke wooden furniture designed to fit your space and style. We use high-quality teak and Sal wood.', image: 'images/business_cuttack_furniture.webp', gallery: ['images/gallery_carpenter_1.webp', 'images/gallery_carpenter_2.webp', 'images/gallery_carpenter_3.webp'] },
    
    // Professional Services
    { id: 4, name: 'Koshal Ladies Tailor', category: 'tailor', location: 'Balangir', lat: 20.7115, lng: 83.4888, phone: '9876543213', tags: ['women-owned'], description: 'Specializing in custom-fit blouses, dresses, and Sambalpuri designs. Run by experienced women tailors who understand modern and traditional styles.', image: 'images/business_koshal_tailor.webp', gallery: ['images/gallery_tailor_1.webp', 'images/gallery_tailor_2.webp', 'images/gallery_tailor_3.webp'] },
    { id: 16, name: 'Quick Clean Laundry', category: 'laundry-service', location: 'Bhubaneswar', lat: 20.2783, lng: 85.8245, phone: '9876543235', tags: ['eco-friendly'], description: 'Professional laundry and dry cleaning services with free pickup and delivery in Bhubaneswar. We use eco-friendly detergents.', image: 'images/business_quick_clean_laundry.webp', gallery: ['images/gallery_laundry_1.webp', 'images/gallery_laundry_2.webp', 'images/gallery_laundry_3.webp'] },
    { id: 21, name: 'Jharsuguda Book Store', category: 'book-store', location: 'Jharsuguda', lat: 21.854, lng: 84.026, phone: '9876543240', tags: [], description: 'A wide collection of academic books, novels, and stationary for all your needs.', image: 'images/business_jharsuguda_books.webp', gallery: ['images/gallery_bookstore_1.webp', 'images/gallery_bookstore_2.webp', 'images/gallery_bookstore_3.webp'] },
    { id: 22, name: 'Bhadrak Bike Service', category: 'bike-repair', location: 'Bhadrak', lat: 21.056, lng: 86.513, phone: '9876543241', tags: [], description: 'Complete servicing and repair for all models of motorcycles and scooters.', image: 'images/business_bhadrak_bike.webp', gallery: ['images/gallery_bike_1.webp', 'images/gallery_bike_2.webp', 'images/gallery_bike_3.webp'] },
    { id: 23, name: 'Steel City Studio', category: 'photographer', location: 'Rourkela', lat: 22.251, lng: 84.86, phone: '9876543242', tags: ['women-owned'], description: 'Professional photography services for weddings, events, and portraits by a team of creative female photographers.', image: 'images/business_steel_city_studio.webp', gallery: ['images/gallery_photo_1.webp', 'images/gallery_photo_2.webp', 'images/gallery_photo_3.webp'] }
];

const allProducts = [
    { id: 101, name: 'Handmade Pattachitra Art', category: 'handicrafts', price: 1200, image: 'images/product_pattachitra_art.webp', shg: 'Maa Durga SHG, Puri', description: 'A beautiful, intricate Pattachitra painting depicting a scene from the Ramayana. Made with natural colors on a specially prepared cotton canvas. A timeless piece of Odia heritage.' },
    { id: 102, name: 'Organic Turmeric Powder', category: 'food', price: 150, image: 'images/product_turmeric_powder.webp', shg: 'Annapurna SHG, Kandhamal', description: 'Pure, aromatic, and potent turmeric powder sourced directly from the famed fields of Kandhamal. Free from pesticides and artificial colors. Adds flavor and health to your meals.' },
    { id: 103, name: 'Sambalpuri Handloom Scarf', category: 'textiles', price: 850, image: 'images/product_sambalpuri_scarf.webp', shg: 'Boyanika Weavers SHG, Sambalpur', description: 'A soft, vibrant Sambalpuri Ikat scarf woven from pure cotton. Features the traditional Bandha tie-and-dye technique, perfect for any occasion.' },
    { id: 104, name: 'Dhokra Metal Figurine', category: 'handicrafts', price: 2500, image: 'images/product_dhokra_figurine.webp', shg: 'Adibasi Crafts SHG, Rayagada', description: 'An exquisite Dhokra metal figurine of a tribal musician, crafted using the ancient lost-wax casting method. A unique and rustic home decor item.' },
    { id: 105, name: 'Sun-dried Mango Pickles', category: 'food', price: 220, image: 'images/product_mango_pickle.webp', shg: 'Maa Tarini SHG, Ganjam', description: 'Spicy and tangy mango pickles made with a traditional family recipe. Prepared with high-quality spices and sun-dried to perfection for a rich, authentic taste.' },
    { id: 106, name: 'Berhampuri Silk Saree', category: 'textiles', price: 4500, image: 'images/product_berhampuri_saree.webp', shg: 'Resham Silpi SHG, Berhampur', description: 'A gorgeous Berhampuri Patta Saree, known for its unique temple (phoda kumbha) borders and pallu. A symbol of elegance and Odia weaving tradition.' },
    { id: 107, name: 'Terracotta Wall Hanging', category: 'handicrafts', price: 700, image: 'images/product_terracotta_hanging.webp', shg: 'Kumbhar Shakti SHG, Balangir', description: 'A set of three hand-painted terracotta wall hangings featuring traditional Odia motifs. Adds a touch of ethnic charm to any wall.' },
    { id: 108, name: 'Ragi & Millet Cookies', category: 'food', price: 180, image: 'images/product_ragi_cookies.webp', shg: 'Koraput Organics SHG, Koraput', description: 'Healthy and delicious cookies made from organic ragi and other millets sourced from Koraput. A nutritious snack for all ages.' },
    { id: 109, name: 'Silver Filigree (Tarakasi) Earrings', category: 'handicrafts', price: 1800, image: 'images/product_silver_filigree_earrings.webp', shg: 'Rupa Tarakasi SHG, Cuttack', description: 'Delicate and stunning silver filigree earrings handcrafted by Cuttack artisans. The intricate Tarakasi work is a testament to their skill.' },
    { id: 110, name: 'Kotpad Handloom Stole', category: 'textiles', price: 1500, image: 'images/product_kotpad_stole.webp', shg: 'Mirgan Weavers SHG, Koraput', description: 'An authentic Kotpad stole dyed with natural colors extracted from the Aal tree. This tribal textile is a GI-tagged product of Odisha.' },
    { id: 111, name: 'Golden Grass Coasters', category: 'handicrafts', price: 450, image: 'images/product_golden_grass_coasters.webp', shg: 'Kaincha SHG, Kendrapara', description: 'A set of six beautiful coasters woven from Golden Grass (Kaincha). Durable, eco-friendly, and perfect for your dining table.' },
    { id: 112, name: 'Spicy Lemon Pickle', category: 'food', price: 190, image: 'images/product_lemon_pickle.webp', shg: 'Maa Mangala SHG, Khurda', description: 'A zesty and spicy lemon pickle that will tingle your taste buds. Made with fresh lemons and a secret blend of spices.' },
    { id: 113, name: 'Bomkai Cotton Dupatta', category: 'textiles', price: 1100, image: 'images/product_bomkai_dupatta.webp', shg: 'Sonepur Weavers SHG, Sonepur', description: 'A beautiful Bomkai cotton dupatta featuring intricate threadwork on the pallu. A perfect blend of tradition and contemporary style.' },
    { id: 114, name: 'Handwoven Sabai Grass Basket', category: 'handicrafts', price: 600, image: 'images/product_sabai_basket.webp', shg: 'Mayurbhanj Tribal Crafts SHG, Baripada', description: 'A sturdy and stylish multi-purpose basket woven from Sabai grass. Ideal for storage or as a decorative piece.' },
    { id: 115, name: 'Gajapati Ladoo', category: 'food', price: 250, image: 'images/product_gajapati_ladoo.webp', shg: 'Paralakhemundi Sweets SHG, Gajapati', description: 'Traditional ladoos made from pure ghee, besan, and nuts, following a recipe from the royal kitchens of Gajapati. A delectable treat.' },
    { id: 116, name: 'Pattachitra Silk Scarf', category: 'textiles', price: 2200, image: 'images/product_pattachitra_scarf.webp', shg: 'Raghurajpur Kalakruti SHG, Puri', description: 'An elegant silk scarf hand-painted with Pattachitra motifs. A wearable piece of art that showcases the fine skills of Odia painters.' }
];

const localWorkers = [
    { id: 201, name: 'Suresh Mohanty', skill: 'Electrician', location: 'Bhubaneswar', lat: 20.2961, lng: 85.8245, rating: 4.8, reviewsCount: 15, phone: '9876543210', bio: 'With over 10 years of experience, I specialize in residential and commercial electrical systems, including new installations, repairs, and safety inspections.', skills: ['House Wiring', 'Fan & Light Installation', 'Inverter Setup', 'Fuse & Breaker Repair'] },
    { id: 202, name: 'Priya Das', skill: 'Tutor', location: 'Cuttack', lat: 20.4625, lng: 85.883, rating: 5.0, reviewsCount: 8, phone: '9876543211', bio: 'I am a passionate educator providing tutoring for Mathematics and Science for students from Class 6 to 10. I focus on building strong conceptual foundations.', skills: ['Mathematics (6-10)', 'Physics (9-10)', 'Chemistry (9-10)', 'Odia & English Medium'] },
    { id: 203, name: 'Rakesh Sahu', skill: 'Mason', location: 'Balangir', lat: 20.7143, lng: 83.4975, rating: 4.5, reviewsCount: 12, phone: '9876543212', bio: 'Experienced mason specializing in all types of brickwork, plastering, and tile setting. I take pride in delivering clean and durable work on time.', skills: ['Bricklaying', 'Plastering', 'Tile & Marble Fitting', 'Concrete Work'] },
    { id: 204, name: 'Anita Besra', skill: 'Cook', location: 'Puri', lat: 19.8135, lng: 85.8312, rating: 4.7, reviewsCount: 10, phone: '9876543213', bio: 'Expert in authentic Odia cuisine for daily meals, parties, and small events. Hygienic and reliable.', skills: ['Odia Cuisine', 'North Indian', 'Event Catering (Small)', 'Daily Cooking'] },
    { id: 205, name: 'Bikash Pradhan', skill: 'Driver', location: 'Sambalpur', lat: 21.4704, lng: 83.9733, rating: 4.9, reviewsCount: 21, phone: '9876543214', bio: 'Professional driver with a commercial license. Available for local and outstation trips with a focus on safety and punctuality.', skills: ['City Driving', 'Highway Driving', 'Commercial License', 'Vehicle Maintenance'] },
    { id: 206, name: 'Sunita Nayak', skill: 'Housekeeping', location: 'Bhubaneswar', lat: 20.2917, lng: 85.8166, rating: 4.6, reviewsCount: 5, phone: '9876543215', bio: 'Reliable and thorough housekeeping services. Available for daily, weekly, or monthly contracts for homes and offices.', skills: ['Deep Cleaning', 'Regular Maintenance', 'Office Cleaning', 'Laundry & Ironing'] },
    { id: 207, name: 'Arun Jena', skill: 'Gardener', location: 'Bhubaneswar', lat: 20.2706, lng: 85.8483, rating: 4.9, reviewsCount: 18, phone: '9876543216', bio: 'Professional gardening and landscaping services. I help create and maintain beautiful green spaces for homes and offices.', skills: ['Landscaping', 'Lawn Maintenance', 'Planting & Pruning', 'Organic Gardening'] },
    { id: 208, name: 'Deepa Mishra', skill: 'Yoga Instructor', location: 'Puri', lat: 19.8052, lng: 85.8248, rating: 5.0, reviewsCount: 25, phone: '9876543217', bio: 'Certified Yoga Alliance instructor offering private and group classes. Specializing in Hatha and Vinyasa yoga for all levels.', skills: ['Hatha Yoga', 'Vinyasa Flow', 'Meditation', 'Pranayama'] },
    { id: 209, name: 'Vikram Singh', skill: 'Web Developer', location: 'Bhubaneswar', lat: 20.3544, lng: 85.8188, rating: 4.7, reviewsCount: 9, phone: '9876543218', bio: 'Freelance web developer building modern and responsive websites for small businesses. Proficient in HTML, CSS, JavaScript, and WordPress.', skills: ['HTML & CSS', 'JavaScript', 'WordPress', 'E-commerce'] },
    { id: 210, name: 'Nabin Barik', skill: 'Painter', location: 'Cuttack', lat: 20.4735, lng: 85.8953, rating: 4.6, reviewsCount: 11, phone: '9876543219', bio: 'Experienced painter for residential and commercial projects. Committed to quality work and timely completion.', skills: ['Interior Painting', 'Exterior Painting', 'Wall Texturing', 'Wood Polishing'] },
    { id: 211, name: 'Ganesh Maharana', skill: 'Carpenter', location: 'Balangir', lat: 20.7100, lng: 83.4950, rating: 4.8, reviewsCount: 14, phone: '9876543220', bio: 'Skilled carpenter with an eye for detail. I create custom furniture and provide all types of wood-related repair services.', skills: ['Custom Furniture', 'Door & Window Repair', 'Polishing', 'Modular Kitchen Setup'] },
    { id: 212, name: 'Santosh Kujur', skill: 'Plumber', location: 'Rourkela', lat: 22.2492, lng: 84.8536, rating: 4.5, reviewsCount: 7, phone: '9876543221', bio: 'Quick and efficient plumbing services in the Steel City. From minor leaks to major installations, no job is too small.', skills: ['Leak Repair', 'Pipe Fitting', 'Water Tank Cleaning', 'Bathroom Fixtures'] },
    { id: 213, name: 'Ramesh Behera', skill: 'AC Repair', location: 'Puri', lat: 19.807, lng: 85.828, rating: 4.7, reviewsCount: 13, phone: '9876543222', bio: 'Expert AC repair and service for all brands. Ensuring cool comfort for homes and hotels in Puri.', skills: ['Split AC Repair', 'Window AC Repair', 'Gas Refilling', 'Annual Maintenance'] },
    { id: 214, name: 'Kishore Patel', skill: 'Electrician', location: 'Sambalpur', lat: 21.465, lng: 83.98, rating: 4.9, reviewsCount: 22, phone: '9876543223', bio: 'A reliable and certified electrician serving the Sambalpur area. I prioritize safety and quality in all my work.', skills: ['Wiring and Re-wiring', 'Meter Installation', 'Appliance Setup', 'Troubleshooting'] },
    { id: 215, name: 'Mamata Sahu', skill: 'Cook', location: 'Berhampur', lat: 19.3137, lng: 84.7939, rating: 4.8, reviewsCount: 19, phone: '9876543224', bio: 'Passionate cook specializing in South Odia and Andhra cuisines. Available for daily cooking and special occasions.', skills: ['South Odia Cuisine', 'Andhra Dishes', 'Vegetarian & Non-Vegetarian', 'Party Cooking'] }
];
